services:
  nomadnet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nomadnet-build
    user: 65532:65532
    volumes:
      - /path/to/nomadnet:/home/nonroot/.nomadnetwork
      - /path/to/reticulum:/home/nonroot/.reticulum
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
    networks:
      - nomadnet_network

networks:
  nomadnet_network:
    driver: bridge
